name: CMake

on:
  push:
    branches:
      - main
      - 'development'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup dependencies
      run: bash ./install/linux/install_dependencies.sh

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        cd tests
        ctest -C $BUILD_TYPE
        
    - name: CodeCov
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config Release
        cd tests
        ./datastructures_tests
        lcov --capture --directory . --output-file coverage.info
        genhtml coverage.info --output-directory .
        bash <(curl -s https://codecov.io/bash) -f coverage.info -t $CODECOV_TOKEN
